version: '3.8'
name: my-mastermind

services:
  app:
    container_name: game
    build: .
    volumes:
      - ./src:/usr/src/app/src
      # - ./src/data:/usr/src/app/src/data
    ports:
      - "4000:4000"
    stdin_open: true # Hold the stdin open
    tty: true # Allocates a pseudo-TTY
    env_file:
      - .env
    # command: [sh, -c, "javac MyMastermind.java && java MyMastermind"]
    command: >
      sh -c "javac -cp '.:src/lib/*' $(find src -name '*.java') && java -cp '.:src/lib/*:src' MyMastermind"
